### ISSUE TITLE
Login Page Form Validation

### ISSUE THREAD

**Issue by FongChanatip** [CSE110-FA24-14/Sync-De-Stress#13]
**As a:** User

**I want:** to know if I input things incorrectly in the login page

**So that:** I can log in correctly

**Can be split:** No

**Blocked by:** Login page component creation

**Split from:** 

### Acceptance Criteria
- [x] In frontend
- [ ] Invalid email should raise error
- [x] email and password is required
- [ ] Form data should be saved to a state with `react-hook-form`

**Comment by g1parkhi** [comment]
https://github.com/user-attachments/assets/1a539973-a770-43c0-a889-55cecd9c551f

**Comment by g1parkhi** [comment]
https://github.com/user-attachments/assets/516b8a92-8465-4f22-afbc-72a2fc6edac3
