### ISSUE TITLE
Signup Page form validation

### ISSUE THREAD

**Issue by FongChanatip** [CSE110-FA24-14/Sync-De-Stress#15]
**As a:** User

**I want:** to be able to create new account

**So that:** I can have my personal account

**Can be split:**

**Blocked by:** 

**Split from:**

### Acceptance Criteria
- [x] In frontend
- [x] Invalid email should raise error
- [x] email and password is required
- [ ] Form data should be saved to a state with `react-hook-form`

**Comment by g1parkhi** [comment]
https://github.com/user-attachments/assets/0cc1883d-64a9-4cac-8cf7-4e213e993dc9
