### ISSUE TITLE
Signup connect with backend

### ISSUE THREAD

**Issue by FongChanatip** [CSE110-FA24-14/Sync-De-Stress#17]
**As a:** User

**I want:** the signup to be linked with the backend

**So that:** my signup information is saved

**Can be split:** No

**Blocked by:** #15 

**Split from:**

### Acceptance Criteria
- [ ] In frontend
- [ ] On submit signup info
- [ ] information should be sent to the backend to check credentials
- [ ] redirect to '/login' if everything goes corrently
- [ ] should display error message if there's an error

**Comment by g1parkhi** [comment]
https://github.com/user-attachments/assets/59fa5de3-4f43-47b8-8e65-1ad393914c9e
