### ISSUE TITLE
Frontend Nav Bar

### ISSUE THREAD

**Issue by nicoleli04** [CSE110-FA24-14/Sync-De-Stress#37]
**As a:** user

**I want:** to have a nav bar

**So that:** I can navigate between the main pages

**Can be split:** maybe

**Blocked by:**

**Split from:**

### Acceptance Criteria
- [x] In frontend
- [x] have 3 options (events, people, profile) and visible on these pages
- [x] clicking each button navigates to that page
- [x] highlights the page currently on

**Comment by galcasid** [comment]
tiny change in detail: switched from pngs to svgs to maintain clarity
