### ISSUE TITLE
[STORY] Create project Skeleton for Backend API Endpoints

### ISSUE THREAD

**Issue by FongChanatip** [CSE110-FA24-14/Sync-De-Stress#4]
**As a:** Dev

**I want:** to have skeleton of a functions for all router and controller

**So that:** future implementation would be easier

**Can be split:** Yes: router and controller

**Blocked by:** None

**Split from:** None

Reference: [Backend reference](https://docs.google.com/spreadsheets/d/1IPbR6bIJ5jfRsL-eTYD9M2F74RDgUW_K_HJMNQpasew/edit?gid=0#gid=0)
[View this commit as example](https://github.com/CSE110-FA24-14/Sync-De-Stress/commit/73e152c2f282cc8a8166c83300e34b2dfdd0d81a)

### Acceptance Criteria
- [ ] In backend
- [ ] There are routers corresponding to all endpoints
- [ ] There are controllers corresponding to all routers returning `302-found` status code

**Comment by nicoleli04** [comment]
Closed with PR #9
