### ISSUE TITLE
RSVP/unRSVP to an event

### ISSUE THREAD

**Issue by nicoleli04** [CSE110-FA24-14/Sync-De-Stress#45]
**As a:** dev/user

**I want:** to RSVP and unRSVP from an event

**So that:** I can register and unregister for the events

**Can be split:**

**Blocked by:**

**Split from:**

### Acceptance Criteria
- [ ] In backend
- [ ] once RSVP'd add event to list of events user has RSVP'd to and remove when unRSVP'd

**Comment by FongChanatip** [comment]
https://github.com/user-attachments/assets/c2468233-f62c-4eac-8072-d7329d207179
