### ISSUE TITLE
[STORY] Create Models for Database

### ISSUE THREAD

**Issue by FongChanatip** [CSE110-FA24-14/Sync-De-Stress#5]
**As a:** Dev

**I want:** To have models for data to store on the database

**So that:** Data could be saved and used accordingly

**Can be split:** Perhaps

**Blocked by:** #2 

**Split from:** None

**Reference:** [Example Model](https://github.com/CSE110-FA24-14/Sync-De-Stress/commit/d8a0a1b9d853a14333bd50059a1bfb790b56b63d)
[Example Interface](https://github.com/CSE110-FA24-14/Sync-De-Stress/commit/7bc13206e6f7c225003848ce92398e299823ae91)

### Acceptance Criteria
- [ ] In backend
- [ ] Create interface for all Events, Profile, and Notification in `src/shared/interface/ModelInterface`
- [ ] Create corresponding model schemas in `src/models/`

**Comment by nicoleli04** [comment]
Closed with PR #10
