### ISSUE TITLE
Backend accept/reject match endpoint

### ISSUE THREAD

**Issue by g1parkhi** [CSE110-FA24-14/Sync-De-Stress#60]
**As a:** Dev,

**I want:** to able to update friend requested field 

**So that:** I could either move person from request to actual friend or remove in case we're rejecting them

**Can be split:**

**Blocked by:**

**Split from:**

### Acceptance Criteria
- [ ] In backend
- [ ] Post /people/match/response
- [ ] Accept user ID and a Boolean value representing accepting/rejecting
- [ ] If accepted, move to friend list and then remove from friend-requested list
- [ ] If rejected, remove from friend-requested list
- [ ] For recipient, replace friend request notification with matched notification
- [ ] For sender, add matched notification

**Comment by FongChanatip** [comment]
https://github.com/user-attachments/assets/556d2fa3-6035-4338-9ad6-1dda9cf361ac
